services:
  api:
    build:
      context: ../..
      dockerfile: apps/docker/backend/Dockerfile.dev
    command: ["--mode=api"]
    volumes:
      - ../../apps/golang/backend:/app
      - sqlite-data:/data/sqlite

  worker:
    build:
      context: ../..
      dockerfile: apps/docker/backend/Dockerfile.dev
    command: ["--mode=worker"]
    volumes:
      - ../../apps/golang/backend:/app
      - sqlite-data:/data/sqlite

  web:
    build:
      context: ../..
      dockerfile: apps/docker/web/Dockerfile.dev
    volumes:
      - ../../apps/node/web:/app
      - /app/node_modules
      - /app/.next
