services:
  api:
    build:
      context: ../..
      dockerfile: apps/docker/backend/Dockerfile.dev
    entrypoint: ["air", "-c", ".air.api.toml"]
    command: []
    volumes:
      - ../../apps/golang/backend:/app
      - ./.data/sqlite:/data/sqlite

  worker:
    build:
      context: ../..
      dockerfile: apps/docker/backend/Dockerfile.dev
    entrypoint: ["air", "-c", ".air.worker.toml"]
    command: []
    volumes:
      - ../../apps/golang/backend:/app
      - ./.data/sqlite:/data/sqlite

  web:
    build:
      context: ../..
      dockerfile: apps/docker/web/Dockerfile.dev
    volumes:
      - ../../apps/node/web:/app
      - ../../apps/node/sdk-tracker:/sdk-tracker
      - /app/node_modules
      - /app/.next
