root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/backend ."
  bin = "./tmp/backend"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]
  delay = 500
  stop_on_error = true
  send_interrupt = true

[log]
  time = true
